jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install -r requirements.txt

      - name: Run StuyTown checker
        run: python stuytown_check.py
        env:
          TWILIO_SID:   ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_FROM:  ${{ secrets.TWILIO_FROM }}
          TWILIO_TO:    ${{ secrets.TWILIO_TO }}
          PRICE_CAP:    ${{ secrets.PRICE_CAP }}
