name: StuyTown price check

on:
  schedule:
    # 9:00 AM America/New_York  ➜  13:00 UTC
    - cron: "0 13 * * *"
  workflow_dispatch:            # keeps the “Run workflow” button

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install -r requirements.txt

      - name: Run StuyTown e-mail checker
        run: python stuytown_email.py
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT:   ${{ secrets.SMTP_PORT }}
          SMTP_USER:   ${{ secrets.SMTP_USER }}
          SMTP_PASS:   ${{ secrets.SMTP_PASS }}
          EMAIL_FROM:  ${{ secrets.EMAIL_FROM }}
          EMAIL_TO:    ${{ secrets.EMAIL_TO }}
          PRICE_CAP:   ${{ secrets.PRICE_CAP }}
